const makeItems = (kind, basePath, sourceUrlFor, entries) =>
  entries.map(([title, slug, group, summary]) => ({
    title,
    slug,
    kind,
    group,
    sourceUrl: sourceUrlFor(slug),
    path: `catalog/${basePath}/${group}/${slug}.md`,
    ...(summary ? { summary } : {}),
  }));

export const principles = makeItems(
  "principle",
  "principles",
  () => "internal://software-design/principles",
  [
    ["Single Responsibility", "single-responsibility", "solid", "A unit should have one clear reason to change."],
    ["Open/Closed", "open-closed", "solid", "Prefer extension points over repeated edits to stable code."],
    ["Liskov Substitution", "liskov-substitution", "solid", "Subtypes must preserve the promises of their base type."],
    ["Interface Segregation", "interface-segregation", "solid", "Clients should depend only on the operations they use."],
    ["Dependency Inversion", "dependency-inversion", "solid", "High-level policy should depend on abstractions, not concrete details."],
    ["DRY", "dry", "core", "Remove knowledge duplication, not harmless repetition."],
    ["KISS", "kiss", "core", "Prefer the simplest design that satisfies the current requirements."],
    ["YAGNI", "yagni", "core", "Do not add abstractions or features before there is a concrete need."],
  ],
);

export const patterns = makeItems(
  "pattern",
  "patterns",
  (slug) => `https://refactoring.guru/design-patterns/${slug}`,
  [
    ["Factory Method", "factory-method", "creational", "Create objects through an overridable method instead of direct construction."],
    ["Abstract Factory", "abstract-factory", "creational", "Create families of related objects without binding clients to concrete classes."],
    ["Builder", "builder", "creational", "Construct complex objects step by step using the same construction process."],
    ["Prototype", "prototype", "creational", "Copy existing objects without depending on their concrete classes."],
    ["Singleton", "singleton", "creational", "Provide one shared instance while controlling access to it."],
    ["Adapter", "adapter", "structural", "Make incompatible interfaces collaborate through a wrapper."],
    ["Bridge", "bridge", "structural", "Split abstraction and implementation so both can vary independently."],
    ["Composite", "composite", "structural", "Treat individual objects and object trees through the same interface."],
    ["Decorator", "decorator", "structural", "Add behavior by wrapping an object rather than changing its class."],
    ["Facade", "facade", "structural", "Expose a simpler interface over a complex subsystem."],
    ["Flyweight", "flyweight", "structural", "Share common immutable state across many lightweight objects."],
    ["Proxy", "proxy", "structural", "Control access to another object through a substitute."],
    ["Chain of Responsibility", "chain-of-responsibility", "behavioral", "Pass a request through handlers until one handles it."],
    ["Command", "command", "behavioral", "Represent a request as an object so it can be queued, logged, or undone."],
    ["Iterator", "iterator", "behavioral", "Traverse a collection without exposing its representation."],
    ["Mediator", "mediator", "behavioral", "Reduce direct dependencies by routing collaboration through a mediator."],
    ["Memento", "memento", "behavioral", "Capture and restore state without exposing internals."],
    ["Observer", "observer", "behavioral", "Notify subscribers when an observed object changes."],
    ["State", "state", "behavioral", "Move state-specific behavior into separate state objects."],
    ["Strategy", "strategy", "behavioral", "Swap interchangeable algorithms behind a stable interface."],
    ["Template Method", "template-method", "behavioral", "Define an algorithm skeleton while letting subclasses override steps."],
    ["Visitor", "visitor", "behavioral", "Separate operations from the object structure they operate on."],
  ],
);

export const smells = makeItems(
  "smell",
  "smells",
  (slug) => `https://refactoring.guru/smells/${slug}`,
  [
    ["Long Method", "long-method", "bloaters"],
    ["Large Class", "large-class", "bloaters"],
    ["Primitive Obsession", "primitive-obsession", "bloaters"],
    ["Long Parameter List", "long-parameter-list", "bloaters"],
    ["Data Clumps", "data-clumps", "bloaters"],
    ["Switch Statements", "switch-statements", "oo-abusers"],
    ["Temporary Field", "temporary-field", "oo-abusers"],
    ["Refused Bequest", "refused-bequest", "oo-abusers"],
    ["Alternative Classes with Different Interfaces", "alternative-classes-with-different-interfaces", "oo-abusers"],
    ["Divergent Change", "divergent-change", "change-preventers"],
    ["Shotgun Surgery", "shotgun-surgery", "change-preventers"],
    ["Parallel Inheritance Hierarchies", "parallel-inheritance-hierarchies", "change-preventers"],
    ["Comments", "comments", "dispensables"],
    ["Duplicate Code", "duplicate-code", "dispensables"],
    ["Lazy Class", "lazy-class", "dispensables"],
    ["Data Class", "data-class", "dispensables"],
    ["Dead Code", "dead-code", "dispensables"],
    ["Speculative Generality", "speculative-generality", "dispensables"],
    ["Feature Envy", "feature-envy", "couplers"],
    ["Inappropriate Intimacy", "inappropriate-intimacy", "couplers"],
    ["Message Chains", "message-chains", "couplers"],
    ["Middle Man", "middle-man", "couplers"],
    ["Incomplete Library Class", "incomplete-library-class", "couplers"],
  ],
);

export const refactorings = makeItems(
  "refactoring",
  "refactorings",
  (slug) => `https://refactoring.guru/${slug}`,
  [
    ["Extract Method", "extract-method", "composing-methods"],
    ["Inline Method", "inline-method", "composing-methods"],
    ["Extract Variable", "extract-variable", "composing-methods"],
    ["Inline Temp", "inline-temp", "composing-methods"],
    ["Replace Temp with Query", "replace-temp-with-query", "composing-methods"],
    ["Split Temporary Variable", "split-temporary-variable", "composing-methods"],
    ["Remove Assignments to Parameters", "remove-assignments-to-parameters", "composing-methods"],
    ["Replace Method with Method Object", "replace-method-with-method-object", "composing-methods"],
    ["Substitute Algorithm", "substitute-algorithm", "composing-methods"],
    ["Move Method", "move-method", "moving-features-between-objects"],
    ["Move Field", "move-field", "moving-features-between-objects"],
    ["Extract Class", "extract-class", "moving-features-between-objects"],
    ["Inline Class", "inline-class", "moving-features-between-objects"],
    ["Hide Delegate", "hide-delegate", "moving-features-between-objects"],
    ["Remove Middle Man", "remove-middle-man", "moving-features-between-objects"],
    ["Introduce Foreign Method", "introduce-foreign-method", "moving-features-between-objects"],
    ["Introduce Local Extension", "introduce-local-extension", "moving-features-between-objects"],
    ["Change Value to Reference", "change-value-to-reference", "organizing-data"],
    ["Change Reference to Value", "change-reference-to-value", "organizing-data"],
    ["Duplicate Observed Data", "duplicate-observed-data", "organizing-data"],
    ["Self Encapsulate Field", "self-encapsulate-field", "organizing-data"],
    ["Replace Data Value with Object", "replace-data-value-with-object", "organizing-data"],
    ["Replace Array with Object", "replace-array-with-object", "organizing-data"],
    ["Change Unidirectional Association to Bidirectional", "change-unidirectional-association-to-bidirectional", "organizing-data"],
    ["Change Bidirectional Association to Unidirectional", "change-bidirectional-association-to-unidirectional", "organizing-data"],
    ["Encapsulate Field", "encapsulate-field", "organizing-data"],
    ["Encapsulate Collection", "encapsulate-collection", "organizing-data"],
    ["Replace Magic Number with Symbolic Constant", "replace-magic-number-with-symbolic-constant", "organizing-data"],
    ["Replace Type Code with Class", "replace-type-code-with-class", "organizing-data"],
    ["Replace Type Code with Subclasses", "replace-type-code-with-subclasses", "organizing-data"],
    ["Replace Type Code with State/Strategy", "replace-type-code-with-state-strategy", "organizing-data"],
    ["Replace Subclass with Fields", "replace-subclass-with-fields", "organizing-data"],
    ["Consolidate Conditional Expression", "consolidate-conditional-expression", "simplifying-conditional-expressions"],
    ["Consolidate Duplicate Conditional Fragments", "consolidate-duplicate-conditional-fragments", "simplifying-conditional-expressions"],
    ["Decompose Conditional", "decompose-conditional", "simplifying-conditional-expressions"],
    ["Replace Conditional with Polymorphism", "replace-conditional-with-polymorphism", "simplifying-conditional-expressions"],
    ["Remove Control Flag", "remove-control-flag", "simplifying-conditional-expressions"],
    ["Replace Nested Conditional with Guard Clauses", "replace-nested-conditional-with-guard-clauses", "simplifying-conditional-expressions"],
    ["Introduce Null Object", "introduce-null-object", "simplifying-conditional-expressions"],
    ["Introduce Assertion", "introduce-assertion", "simplifying-conditional-expressions"],
    ["Add Parameter", "add-parameter", "simplifying-method-calls"],
    ["Remove Parameter", "remove-parameter", "simplifying-method-calls"],
    ["Rename Method", "rename-method", "simplifying-method-calls"],
    ["Separate Query from Modifier", "separate-query-from-modifier", "simplifying-method-calls"],
    ["Parameterize Method", "parameterize-method", "simplifying-method-calls"],
    ["Introduce Parameter Object", "introduce-parameter-object", "simplifying-method-calls"],
    ["Preserve Whole Object", "preserve-whole-object", "simplifying-method-calls"],
    ["Remove Setting Method", "remove-setting-method", "simplifying-method-calls"],
    ["Replace Parameter with Explicit Methods", "replace-parameter-with-explicit-methods", "simplifying-method-calls"],
    ["Replace Parameter with Method Call", "replace-parameter-with-method-call", "simplifying-method-calls"],
    ["Hide Method", "hide-method", "simplifying-method-calls"],
    ["Replace Constructor with Factory Method", "replace-constructor-with-factory-method", "simplifying-method-calls"],
    ["Replace Error Code with Exception", "replace-error-code-with-exception", "simplifying-method-calls"],
    ["Replace Exception with Test", "replace-exception-with-test", "simplifying-method-calls"],
    ["Pull Up Field", "pull-up-field", "dealing-with-generalization"],
    ["Pull Up Method", "pull-up-method", "dealing-with-generalization"],
    ["Pull Up Constructor Body", "pull-up-constructor-body", "dealing-with-generalization"],
    ["Push Down Field", "push-down-field", "dealing-with-generalization"],
    ["Push Down Method", "push-down-method", "dealing-with-generalization"],
    ["Extract Subclass", "extract-subclass", "dealing-with-generalization"],
    ["Extract Superclass", "extract-superclass", "dealing-with-generalization"],
    ["Extract Interface", "extract-interface", "dealing-with-generalization"],
    ["Collapse Hierarchy", "collapse-hierarchy", "dealing-with-generalization"],
    ["Form Template Method", "form-template-method", "dealing-with-generalization"],
    ["Replace Inheritance with Delegation", "replace-inheritance-with-delegation", "dealing-with-generalization"],
    ["Replace Delegation with Inheritance", "replace-delegation-with-inheritance", "dealing-with-generalization"],
  ],
);

export const allItems = [...principles, ...patterns, ...smells, ...refactorings];
